import type { StrapiApp } from '@strapi/strapi/admin';

export default {
  config: {
    locales: ['ru'],
    translations: {
      ru: {
        'actions.clone.label': 'Дублировать',
        'actions.delete.label': 'Удалить запись',
        'actions.discard.label': 'Отменить изменения',
        'actions.edit.label': 'Редактировать',
        'actions.unpublish.dialog.option.keep-draft': 'Снять с публикации и сохранить черновик',
        'actions.unpublish.dialog.option.replace-draft': 'Снять с публикации и заменить черновик',
        'components.AddFilterCTA.add': 'Фильтры',
        'components.AddFilterCTA.hide': 'Фильтры',
        'components.FilterOptions.button.apply': 'Применить',
        'components.FiltersPickWrapper.PluginHeader.actions.apply': 'Применить',
        'components.FiltersPickWrapper.PluginHeader.actions.clearAll': 'Очистить все',
        'components.FiltersPickWrapper.PluginHeader.title.filter': 'Фильтры',
        'components.Search.placeholder': 'Поиск записи...',
        'components.Select.draft-info-title': 'Черновик',
        'components.Select.publish-info-title': 'Опубликован',
        'containers.edit.header.more-actions': 'Еще действия',
        'containers.edit.panels.default.more-actions': 'Еще действия с записью',
        'containers.edit.panels.default.title': 'Запись',
        'containers.edit.tabs.draft': 'Черновик',
        'containers.edit.tabs.label': 'Статус записи',
        'containers.edit.tabs.published': 'Опубликовано',
        'containers.edit.title.new': 'Создать запись',
        'containers.Edit.delete': 'Удалить',
        'containers.Edit.delete-entry': 'Удалить запись',
        'containers.Edit.returnList': 'Вернуться к списку',
        'containers.Edit.submit': 'Сохранить',
        'containers.EditView.add.new-entry': 'Добавить запись',
        'containers.List.draft': 'Черновик',
        'containers.List.modified': 'Изменен',
        'containers.List.published': 'Опубликован',
        'containers.list.autoCloneModal.create': 'Создать',
        'containers.list.autoCloneModal.header': 'Дублировать',
        'containers.list.displayedFields': 'Поля в таблице',
        'containers.list.filters.status': 'Статус',
        'containers.list.table-headers.publishedAt': 'Статус',
        'containers.list.table.row-actions': 'Действия',
        'HeaderLayout.button.label-add-entry': 'Создать новую запись',
        'pages.ListView.header-subtitle': 'Найдено записей: {number}',
        'success.record.publish': 'Опубликовано',
        'success.record.save': 'Сохранено',
        'success.record.unpublish': 'Снято с публикации',
        'global.edit': 'Редактировать',
        'global.delete': 'Удалить',
        'global.save': 'Сохранить',
        'global.publish': 'Опубликовать',
        'content-manager.content-types.api::article.article.title': 'Заголовок',
        'content-manager.content-types.api::article.article.slug': 'Адрес страницы',
        'content-manager.content-types.api::article.article.excerpt': 'Краткое описание',
        'content-manager.content-types.api::article.article.content': 'Текст статьи',
        'content-manager.content-types.api::article.article.date': 'Дата публикации',
        'content-manager.content-types.api::article.article.topic': 'Категория',
        'content-manager.content-types.api::article.article.cover': 'Обложка',
        'content-manager.content-types.api::news-item.news-item.title': 'Заголовок',
        'content-manager.content-types.api::news-item.news-item.slug': 'Адрес страницы',
        'content-manager.content-types.api::news-item.news-item.excerpt': 'Краткое описание',
        'content-manager.content-types.api::news-item.news-item.content': 'Текст новости',
        'content-manager.content-types.api::news-item.news-item.date': 'Дата публикации',
        'content-manager.content-types.api::news-item.news-item.badge': 'Бейдж',
        'content-manager.content-types.api::news-item.news-item.cover': 'Обложка',
        'content-manager.content-types.api::news-item.news-item.sideImage': 'Картинка справа от текста',
        'content-manager.content-types.api::video.video.title': 'Название',
        'content-manager.content-types.api::video.video.description': 'Описание для страницы и SEO',
        'content-manager.content-types.api::video.video.youtubeUrl': 'Ссылка YouTube',
        'content-manager.content-types.api::video.video.rutubeUrl': 'Ссылка Rutube',
        'content-manager.content-types.api::video.video.previewUrl': 'Превью',
        'content-manager.content-types.api::video.video.tag': 'Тег раздела',
        'content-manager.content-types.api::video.video.date': 'Дата выпуска',
        'content-manager.content-types.api::video.video.order': 'Порядок отображения',
        'content-manager.content-types.api::service.service.title': 'Название',
        'content-manager.content-types.api::service.service.slug': 'Адрес страницы',
        'content-manager.content-types.api::service.service.description': 'Краткое описание',
        'content-manager.content-types.api::service.service.content': 'Текст услуги',
        'content-manager.content-types.api::service.service.pageContent': 'Контент страницы',
        'content-manager.content-types.api::service.service.number': 'Номер',
        'content-manager.content-types.api::service.service.order': 'Порядок',
        'content-manager.content-types.api::service.service.price': 'Цена',
        'content-manager.content-types.api::service.service.icon': 'Иконка',
      },
    },
  },
  bootstrap(_app: StrapiApp) {},
};
